name: Pre-Commit Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      -'*'

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '^3.12'

      - name: Install dependencies
        run: |
          pip install pre-commit
          pre-commit install

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: Run Pre-Commit on Changed Files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            pre-commit run --files "$file" || exit 1
          done
